var mongoose = require("mongoose");
var passportLocalMongoose = require("passport-local-mongoose");
var fPaper = new mongoose.Schema({
	username: {type: String, unique: false},
	semester: String,
	subjectcode: String,
	a1: {type: String, required: true},
	b1: String,
	c1: String,
	d1: String,
	a2: {type: String, required: true},
	b2: String,
	c2: String,
	d2: String,
	a3: {type: String, required: true},
	b3: String,
	c3: String,
	d3: String,
	a4: {type: String, required: true},
	b4: String,
	c4: String,
	d4: String,
	a5: {type: String, required: true},
	b5: String,
	c5: String,
	d5: String,
	a1m: {type: Number, required: true},
	b1m: Number,
	c1m: Number,
	d1m: Number,
	a2m: {type: Number, required: true},
	b2m: Number,
	c2m: Number,
	d2m: Number,
	a3m: {type: Number, required: true},
	b3m: Number,
	c3m: Number,
	d3m: Number,
	a4m: {type: Number, required: true},
	b4m: Number,
	c4m: Number,
	d4m: Number,
	a5m: {type: Number, required: true},
	b5m: Number,
	c5m: Number,
	d5m: Number,
	ca1: {type: String, required: true},
	cb1: String,
	cc1: String,
	cd1: String,
	ca2: {type: String, required: true},
	cb2: String,
	cc2: String,
	cd2: String,
	ca3: {type: String, required: true},
	cb3: String,
	cc3: String,
	cd3: String,
	ca4: {type: String, required: true},
	cb4: String,
	cc4: String,
	cd4: String,
	ca5: {type: String, required: true},
	cb5: String,
	cc5: String,
	cd5: String,
	ba1: {type: String, required: true},
	bb1: String,
	bc1: String,
	bd1: String,
	ba2: {type: String, required: true},
	bb2: String,
	bc2: String,
	bd2: String,
	ba3: {type: String, required: true},
	bb3: String,
	bc3: String,
	bd3: String,
	ba4: {type: String, required: true},
	bb4: String,
	bc4: String,
	bd4: String,
	ba5: {type: String, required: true},
	bb5: String,
	bc5: String,
	bd5: String,
	key: String,
	d: String,
});
fPaper.plugin(passportLocalMongoose);
module.exports = mongoose.model("FPaper", fPaper);